version: '3.6'

services:
  device-app:
    image: device-energy  # Replace with the actual Spring Boot application image
    container_name: device-app
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres2:5432/yourdb  # Update with your DB name
      SPRING_DATASOURCE_USERNAME: yourdbuser
      SPRING_DATASOURCE_PASSWORD: yourdbpassword
    depends_on:
      - postgres2
    networks:
      - mynetwork

  postgres2:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdb  # Update with your DB name
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
    ports:
      - "5434:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data2
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true

volumes:
  postgres_data2:
