version: '3.6'

services:
  user-app:
    image: user-energy
    container_name: user-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/yourdb
      SPRING_DATASOURCE_USERNAME: yourdbuser
      SPRING_DATASOURCE_PASSWORD: yourdbpassword
    depends_on:
      - postgres
    networks:
      - mynetwork

  device-app:
    image: device-energy
    container_name: device-app
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres2:5432/yourdb
      SPRING_DATASOURCE_USERNAME: yourdbuser
      SPRING_DATASOURCE_PASSWORD: yourdbpassword
    depends_on:
      - postgres2
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdb
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  postgres2:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdb
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
    ports:
      - "5434:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data2
    networks:
      - mynetwork
  react:
    image: energy-fe
    ports:
      - "80:80"
    environment:
      - BACKEND=172.30.0.2
    networks:
      - mynetwork



networks:
  mynetwork:
    external: true

volumes:
  postgres_data:
  postgres_data2:
